# Site settings
title: ThinkWork.org
email: your-email@domain.com
url: https://example.github.io
description: "Thinkwork.org is upcoming home of home to research, training, and outreach activities that promote employment for individuals with intellectual and developmental disabilities (IDD).

We are funded by the National Institute on Disability and Rehabilitation Research in the US Department of Education.

The RRTC is a project of the Institute for Community Inclusion at the University of Massachusetts Boston."
baseurl:
# Contact form: comment the line below if you want to stick with the default PHP contact form

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d5d5d5 #d5d5d5
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Institute for Community Inclusion Umass Boston
  location: Boston
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
